### ISSUE TITLE
As an admin I want to edit a specific customer’s information so that I can ensure that the details are up to date.

### ISSUE THREAD

**Issue by IsabelHaataja** [KYH-Net23/AdminRepository#9]
Authors: Kimmo Ahola & Isabel Haataja

**Acceptance Criteria:**
- [ ] Admins should receive the customer information from a database.
- [ ] Admins can save the changes to a database.
- [ ] The user account type (admin, customer) can not be updated.
- [ ] Changes should not be saved if the fields are invalid.
- [ ] Error messages should be displayed if the user tries to save incorrect information.
- [ ] There can not be duplicates of Email.

**Tasks:**
- [ ] Implement an “edit” button that loads an edit form.
- [ ] Load the customer data from an API.
- [ ] Implement an edit form with validation for the fields.
- [ ] Implement an edit customer model with data validation.
- Name
- Email
- Birthdate
- Gender
- Date Changed
- [ ] Implement a version history of changes.
- [ ] Implement a “Save” button
- [ ] Implement a “Cancel” button

**Activity Diagram:** 
![Image](https://github.com/user-attachments/assets/fd2e3747-c0c4-4cd6-bf89-3d58770533b4)
